import type { DraftTerm } from "./schema";

/**
 * Redaksjonell kø: begreper som ennå ikke har komplett innhold.
 *
 * Disse publiseres ikke. De har ingen offentlig side, og er usynlige i søk,
 * kategorilister, A–Å og forrige/neste. Et begrep flyttes hit ut ved å få sin
 * egen fil under `terms/`, med forklaring, demonstrasjon og dybde på plass.
 *
 * Definisjonene er hentet fra designprototypen og er ikke faglig kvalitetssikret.
 */
export const draftTerms: DraftTerm[] = [
  {
    slug: "repeterbarhet",
    title: "Repeterbarhet",
    category: "kvalitet",
    definition: "Presisjon under helt like forhold: samme operatør, instrument og dag.",
    aliases: ["within-run", "serie", "gjentak"],
    status: "utkast",
  },
  {
    slug: "reproduserbarhet",
    title: "Reproduserbarhet",
    category: "kvalitet",
    definition: "Presisjon mellom laboratorier.",
    aliases: ["between-lab", "ringtest"],
    status: "utkast",
  },
  {
    slug: "intermediar",
    title: "Intermediær presisjon",
    category: "kvalitet",
    definition: "Presisjon innen samme laboratorium, men over ulike dager og operatører.",
    aliases: ["mellomliggende", "between-run"],
    status: "utkast",
  },
  {
    slug: "skjevhet",
    title: "Systematisk skjevhet mot referansemateriale",
    category: "kvalitet",
    definition: "Den systematiske forskjellen mellom metodens forventede resultat og en akseptert referanseverdi, uttrykt som absolutt eller relativt avvik.",
    aliases: ["bias", "systematisk", "feil", "recovery"],
    status: "utkast",
  },
  {
    slug: "gjenvinning",
    title: "Gjenvinning",
    category: "kvalitet",
    definition: "Hvor stor andel av et tilsatt stoff metoden finner igjen.",
    aliases: ["recovery", "utbytte", "tilsetning", "spiking"],
    status: "utkast",
  },
  {
    slug: "robusthet",
    title: "Robusthet",
    category: "kvalitet",
    definition: "Hvor lite resultatet påvirkes av små, tilsiktede endringer i metoden.",
    aliases: ["ruggedness", "tåler", "variasjon"],
    status: "utkast",
  },
  {
    slug: "selektivitet",
    title: "Selektivitet",
    category: "kvalitet",
    definition: "Metodens evne til å måle analytten uforstyrret av andre komponenter.",
    aliases: ["interferens", "spesifisitet"],
    status: "utkast",
  },
  {
    slug: "spesifisitet",
    title: "Spesifisitet",
    category: "kvalitet",
    definition: "Å måle bare én analytt, uten bidrag fra noe annet.",
    aliases: ["selektiv", "entydig"],
    status: "utkast",
  },
  {
    slug: "sporbarhet",
    title: "Sporbarhet",
    category: "kvalitet",
    definition: "En ubrutt kjede av sammenligninger tilbake til en nasjonal eller internasjonal referanse.",
    aliases: ["traceability", "kjede", "si-enhet"],
    status: "utkast",
  },
  {
    slug: "validering",
    title: "Validering",
    category: "kvalitet",
    definition: "Dokumentasjon på at en metode gjør det den skal, for det formålet den skal brukes til.",
    aliases: ["validere", "metodevalidering", "krav"],
    status: "utkast",
  },
  {
    slug: "verifisering",
    title: "Verifisering",
    category: "kvalitet",
    definition: "Å kontrollere at en allerede validert metode fungerer hos oss.",
    aliases: ["verifisere", "innføring"],
    status: "utkast",
  },
  {
    slug: "utvidet",
    title: "Utvidet måleusikkerhet med dekningsfaktor",
    category: "kvalitet",
    definition: "Standardusikkerheten multiplisert med en dekningsfaktor k, slik at intervallet dekker en valgt andel av mulige resultater, vanligvis omtrent 95 prosent ved k lik 2.",
    aliases: ["U", "k=2", "dekningsnivå", "konfidens"],
    status: "utkast",
  },
  {
    slug: "dekningsfaktor",
    title: "Dekningsfaktor",
    category: "kvalitet",
    definition: "Tallet standardusikkerheten multipliseres med for å få et intervall med ønsket dekning.",
    aliases: ["k", "faktor", "2"],
    status: "utkast",
  },
  {
    slug: "kontrollkort",
    title: "Kontrollkort",
    category: "kvalitet",
    definition: "En graf over kontrollprøver over tid, som viser om metoden holder seg stabil.",
    aliases: ["shewhart", "kontrollgrense", "trend"],
    status: "utkast",
  },
  {
    slug: "folsomhet",
    title: "Følsomhet",
    category: "kvalitet",
    definition: "Hvor mye signalet endrer seg når konsentrasjonen endrer seg — kurvens stigningstall.",
    aliases: ["sensitivitet", "stigningstall", "slope"],
    status: "utkast",
  },
  {
    slug: "kalibreringskurve",
    title: "Kalibreringskurve",
    category: "kalibrering",
    definition: "Sammenhengen mellom kjent konsentrasjon og målt signal, målt opp med standarder.",
    aliases: ["standardkurve", "kurve", "regresjonslinje"],
    status: "utkast",
  },
  {
    slug: "kvantifiseringsgrense",
    title: "Kvantifiseringsgrense",
    category: "kalibrering",
    definition: "Den minste mengden som kan tallfestes med akseptabel usikkerhet.",
    aliases: ["loq", "rapporteringsgrense"],
    status: "utkast",
  },
  {
    slug: "responsfaktor",
    title: "Responsfaktor",
    category: "kalibrering",
    definition: "Signal per mengde stoff, brukt til å sammenligne analytter.",
    aliases: ["rf", "forhold"],
    status: "utkast",
  },
  {
    slug: "arbeidsomrade",
    title: "Arbeidsområde",
    category: "kalibrering",
    definition: "Konsentrasjonsområdet der metoden er dokumentert å fungere.",
    aliases: ["område", "range", "gyldighet"],
    status: "utkast",
  },
  {
    slug: "ettpunkts",
    title: "Ettpunktskalibrering",
    category: "kalibrering",
    definition: "Kalibrering mot én enkelt standard, med antakelse om at kurven går gjennom null.",
    aliases: ["én", "standard", "forenklet"],
    status: "utkast",
  },
  {
    slug: "vektet",
    title: "Vektet regresjon",
    category: "kalibrering",
    definition: "Regresjon der lave punkter vektes tyngre, fordi spredningen øker med konsentrasjonen.",
    aliases: ["1/x", "vekting", "heteroskedastisitet"],
    status: "utkast",
  },
  {
    slug: "nullpunkt",
    title: "Nullpunkt",
    category: "kalibrering",
    definition: "Signalet kurven starter på når konsentrasjonen er null.",
    aliases: ["skjæringspunkt", "intercept"],
    status: "utkast",
  },
  {
    slug: "drift",
    title: "Drift",
    category: "kalibrering",
    definition: "Langsom forskyvning av signalet gjennom en analyseserie.",
    aliases: ["glidning", "ustabilitet"],
    status: "utkast",
  },
  {
    slug: "kontrollprove",
    title: "Kontrollprøve",
    category: "kalibrering",
    definition: "En prøve med kjent innhold som analyseres sammen med de ukjente.",
    aliases: ["qc", "kontroll"],
    status: "utkast",
  },
  {
    slug: "ekstern",
    title: "Ekstern kalibrering",
    category: "kalibrering",
    definition: "Kalibrering med standarder laget separat, utenfor prøvematriksen.",
    aliases: ["standardserie"],
    status: "utkast",
  },
  {
    slug: "matrikstilpasset",
    title: "Matrikstilpasset kalibrering",
    category: "kalibrering",
    definition: "Kalibrering der standardene lages i samme type matriks som prøvene.",
    aliases: ["matrix-matched", "matriks"],
    status: "utkast",
  },
  {
    slug: "ionesuppresjon",
    title: "Ionesuppresjon",
    category: "prove",
    definition: "Demping av signalet fordi andre komponenter konkurrerer om ionisering.",
    aliases: ["suppresjon", "lc-ms", "ionekilde"],
    status: "utkast",
  },
  {
    slug: "ioneforsterkning",
    title: "Ioneforsterkning",
    category: "prove",
    definition: "Det motsatte: matriksen gjør signalet sterkere enn det skulle være.",
    aliases: ["enhancement", "forsterkning"],
    status: "utkast",
  },
  {
    slug: "interferens",
    title: "Interferens",
    category: "prove",
    definition: "Et annet stoff som bidrar til signalet og forveksles med analytten.",
    aliases: ["forstyrrelse", "overlapp"],
    status: "utkast",
  },
  {
    slug: "kontaminering",
    title: "Kontaminering",
    category: "prove",
    definition: "Uønsket tilførsel av analytten fra utstyr, reagenser eller omgivelser.",
    aliases: ["forurensning"],
    status: "utkast",
  },
  {
    slug: "krysskontaminering",
    title: "Krysskontaminering",
    category: "prove",
    definition: "Rester fra en prøve som følger med inn i den neste.",
    aliases: ["carry-over", "overslag"],
    status: "utkast",
  },
  {
    slug: "bakgrunnssignal",
    title: "Bakgrunnssignal",
    category: "prove",
    definition: "Signalet instrumentet gir uten at analytten er der.",
    aliases: ["baseline", "grunnlinje", "støy"],
    status: "utkast",
  },
  {
    slug: "matriksblank",
    title: "Matriksblank",
    category: "prove",
    definition: "Ekte matriks uten analytten, brukt for å se hva matriksen selv bidrar med.",
    aliases: ["blank", "matriks"],
    status: "utkast",
  },
  {
    slug: "provelagring",
    title: "Prøvelagring",
    category: "prove",
    definition: "Oppbevaring som bevarer prøven uendret til analysen er gjort.",
    aliases: ["holdbarhet", "frysing", "stabilitet"],
    status: "utkast",
  },
  {
    slug: "varians",
    title: "Varians",
    category: "statistikk",
    definition: "Standardavviket kvadrert.",
    aliases: ["s2", "spredningsmål"],
    status: "utkast",
  },
  {
    slug: "gjennomsnitt",
    title: "Gjennomsnitt",
    category: "statistikk",
    definition: "Summen av målingene delt på antallet.",
    aliases: ["middelverdi", "snitt", "x-strek"],
    status: "utkast",
  },
  {
    slug: "median",
    title: "Median",
    category: "statistikk",
    definition: "Den midterste verdien når målingene sorteres.",
    aliases: ["midtverdi"],
    status: "utkast",
  },
  {
    slug: "konfidensintervall",
    title: "Konfidensintervall",
    category: "statistikk",
    definition: "Et intervall som med en valgt sannsynlighet inneholder den sanne verdien.",
    aliases: ["ki", "95", "%", "intervall"],
    status: "utkast",
  },
  {
    slug: "ttest",
    title: "t-test",
    category: "statistikk",
    definition: "En test for om to gjennomsnitt er forskjellige mer enn tilfeldig variasjon tilsier.",
    aliases: ["student", "signifikans"],
    status: "utkast",
  },
  {
    slug: "ftest",
    title: "F-test",
    category: "statistikk",
    definition: "En test for om to spredninger er forskjellige.",
    aliases: ["varianstest"],
    status: "utkast",
  },
  {
    slug: "regresjon",
    title: "Regresjon",
    category: "statistikk",
    definition: "Å tilpasse en linje eller kurve til måledata.",
    aliases: ["minste", "kvadrater", "tilpasning"],
    status: "utkast",
  },
  {
    slug: "korrelasjon",
    title: "Korrelasjonskoeffisient",
    category: "statistikk",
    definition: "Et tall for hvor sterkt to størrelser samvarierer.",
    aliases: ["r", "r2", "samvariasjon"],
    status: "utkast",
  },
  {
    slug: "uteligger",
    title: "Uteligger",
    category: "statistikk",
    definition: "En måling som skiller seg så mye fra de andre at den mistenkes å være feil.",
    aliases: ["outlier", "grubbs"],
    status: "utkast",
  },
  {
    slug: "normalfordeling",
    title: "Normalfordeling",
    category: "statistikk",
    definition: "Den klokkeformede fordelingen mange måleserier følger.",
    aliases: ["gauss", "klokkekurve"],
    status: "utkast",
  },
  {
    slug: "frihetsgrader",
    title: "Frihetsgrader",
    category: "statistikk",
    definition: "Antall uavhengige opplysninger som er tilgjengelige i et estimat.",
    aliases: ["df", "n-1"],
    status: "utkast",
  },
  {
    slug: "signifikansniva",
    title: "Signifikansnivå",
    category: "statistikk",
    definition: "Risikoen man aksepterer for å konkludere feil.",
    aliases: ["alfa", "0,05", "p-verdi"],
    status: "utkast",
  },
  {
    slug: "minstekvadrater",
    title: "Minste kvadraters metode",
    category: "statistikk",
    definition: "Tilpasning som gjør summen av kvadrerte avvik minst mulig.",
    aliases: ["ols", "regresjon"],
    status: "utkast",
  },
  {
    slug: "retensjonstid",
    title: "Retensjonstid",
    category: "separasjon",
    definition: "Tiden fra injeksjon til stoffet kommer ut av kolonnen.",
    aliases: ["rt", "tid", "identifikasjon"],
    status: "utkast",
  },
  {
    slug: "mobilfase",
    title: "Mobilfase",
    category: "separasjon",
    definition: "Væsken eller gassen som fører prøven gjennom kolonnen.",
    aliases: ["eluent", "bæregass"],
    status: "utkast",
  },
  {
    slug: "stasjonarfase",
    title: "Stasjonærfase",
    category: "separasjon",
    definition: "Materialet i kolonnen som stoffene vekselvirker med.",
    aliases: ["kolonnemateriale", "c18"],
    status: "utkast",
  },
  {
    slug: "gradient",
    title: "Gradienteluering",
    category: "separasjon",
    definition: "Eluering der mobilfasens sammensetning endres underveis.",
    aliases: ["gradient", "program"],
    status: "utkast",
  },
  {
    slug: "isokratisk",
    title: "Isokratisk eluering",
    category: "separasjon",
    definition: "Eluering med konstant sammensetning av mobilfasen.",
    aliases: ["konstant"],
    status: "utkast",
  },
  {
    slug: "toppbredde",
    title: "Toppbredde",
    category: "separasjon",
    definition: "Hvor bred en kromatografisk topp er ved en gitt høyde.",
    aliases: ["bredde", "halvhøyde"],
    status: "utkast",
  },
  {
    slug: "haledannelse",
    title: "Haledannelse",
    category: "separasjon",
    definition: "Når toppen blir usymmetrisk med en hale bakover.",
    aliases: ["tailing", "asymmetri"],
    status: "utkast",
  },
  {
    slug: "platetall",
    title: "Platetall",
    category: "separasjon",
    definition: "Et mål på kolonnens effektivitet — hvor smale topper den gir.",
    aliases: ["n", "effektivitet"],
    status: "utkast",
  },
  {
    slug: "selektivitetsfaktor",
    title: "Selektivitetsfaktor",
    category: "separasjon",
    definition: "Forholdet mellom to stoffers retensjon, altså hvor ulikt de holdes igjen.",
    aliases: ["alfa", "separasjonsfaktor"],
    status: "utkast",
  },
  {
    slug: "dodvolum",
    title: "Dødvolum",
    category: "separasjon",
    definition: "Volumet i systemet som ikke bidrar til separasjonen.",
    aliases: ["void", "ekstrakolonne"],
    status: "utkast",
  },
  {
    slug: "elueringsrekkefolge",
    title: "Elueringsrekkefølge",
    category: "separasjon",
    definition: "Rekkefølgen stoffene kommer ut av kolonnen i.",
    aliases: ["rekkefølge"],
    status: "utkast",
  },
  {
    slug: "injeksjonsvolum",
    title: "Injeksjonsvolum",
    category: "separasjon",
    definition: "Mengden prøve som settes på kolonnen.",
    aliases: ["injeksjon", "volum"],
    status: "utkast",
  },
  {
    slug: "signalstoy",
    title: "Signal-støy-forhold",
    category: "deteksjon",
    definition: "Toppens høyde sammenlignet med bakgrunnsstøyen.",
    aliases: ["s/n", "snr", "støy"],
    status: "utkast",
  },
  {
    slug: "massespektrometri",
    title: "Massespektrometri",
    category: "deteksjon",
    definition: "Deteksjon ved å måle masse og ladning til ioner.",
    aliases: ["ms", "masse", "ioner"],
    status: "utkast",
  },
  {
    slug: "ionisering",
    title: "Ionisering",
    category: "deteksjon",
    definition: "Trinnet der molekyler gjøres om til ioner slik at de kan måles.",
    aliases: ["esi", "apci", "elektrospray"],
    status: "utkast",
  },
  {
    slug: "mrm",
    title: "MRM",
    category: "deteksjon",
    definition: "Målemodus der bare utvalgte overganger mellom moderion og fragment følges.",
    aliases: ["srm", "overgang", "triple", "quad"],
    status: "utkast",
  },
  {
    slug: "simmodus",
    title: "SIM-modus",
    category: "deteksjon",
    definition: "Målemodus der bare utvalgte masser registreres, for høyere følsomhet.",
    aliases: ["selected", "ion"],
    status: "utkast",
  },
  {
    slug: "lcms",
    title: "LC-MS",
    category: "deteksjon",
    definition: "Væskekromatografi koblet til massespektrometer.",
    aliases: ["lcms", "hplc-ms"],
    status: "utkast",
  },
  {
    slug: "gcms",
    title: "GC-MS",
    category: "deteksjon",
    definition: "Gasskromatografi koblet til massespektrometer.",
    aliases: ["gcms"],
    status: "utkast",
  },
  {
    slug: "uvdetektor",
    title: "UV-detektor",
    category: "deteksjon",
    definition: "Detektor som måler hvor mye lys prøven absorberer.",
    aliases: ["absorbans", "diode", "array"],
    status: "utkast",
  },
  {
    slug: "fid",
    title: "Flammeionisasjonsdetektor",
    category: "deteksjon",
    definition: "GC-detektor som måler ioner dannet når stoffet brennes i en flamme.",
    aliases: ["fid", "flamme"],
    status: "utkast",
  },
  {
    slug: "ledningsevne",
    title: "Ledningsevnedetektor",
    category: "deteksjon",
    definition: "Detektor som måler væskens evne til å lede strøm.",
    aliases: ["konduktivitet", "ionekromatografi"],
    status: "utkast",
  },
  {
    slug: "masseopplosning",
    title: "Masseoppløsning",
    category: "deteksjon",
    definition: "Instrumentets evne til å skille to nesten like masser.",
    aliases: ["resolving", "power", "hrms"],
    status: "utkast",
  },
  {
    slug: "fragmentering",
    title: "Fragmentering",
    category: "deteksjon",
    definition: "Når ioner brytes opp i mindre biter som gir et gjenkjennelig mønster.",
    aliases: ["fragment", "ms/ms"],
    status: "utkast",
  },
  {
    slug: "representativ",
    title: "Representativ prøve",
    category: "provetaking",
    definition: "En prøve som faktisk speiler det partiet den er tatt fra.",
    aliases: ["representativitet", "uttak", "parti"],
    status: "utkast",
  },
  {
    slug: "delprove",
    title: "Delprøve",
    category: "provetaking",
    definition: "En mindre porsjon tatt ut av en større prøve.",
    aliases: ["subprøve", "deling"],
    status: "utkast",
  },
  {
    slug: "homogenisering",
    title: "Homogenisering",
    category: "provetaking",
    definition: "Å gjøre prøven jevn før uttak, slik at delprøvene blir like.",
    aliases: ["blanding", "maling"],
    status: "utkast",
  },
  {
    slug: "ekstraksjon",
    title: "Ekstraksjon",
    category: "provetaking",
    definition: "Å hente analytten ut av prøven og over i en løsning.",
    aliases: ["spe", "væske-væske", "utvinning"],
    status: "utkast",
  },
  {
    slug: "oppkonsentrering",
    title: "Oppkonsentrering",
    category: "provetaking",
    definition: "Å gjøre analytten mer konsentrert før måling.",
    aliases: ["inndamping", "berikelse"],
    status: "utkast",
  },
  {
    slug: "fortynning",
    title: "Fortynning",
    category: "provetaking",
    definition: "Å gjøre prøven svakere ved å tilsette løsemiddel.",
    aliases: ["dilusjon"],
    status: "utkast",
  },
  {
    slug: "fortynningsfaktor",
    title: "Fortynningsfaktor",
    category: "provetaking",
    definition: "Tallet resultatet må multipliseres med for å komme tilbake til opprinnelig prøve.",
    aliases: ["df", "faktor"],
    status: "utkast",
  },
  {
    slug: "filtrering",
    title: "Filtrering",
    category: "provetaking",
    definition: "Å fjerne partikler før prøven settes på instrumentet.",
    aliases: ["filter", "membran"],
    status: "utkast",
  },
  {
    slug: "oppslutning",
    title: "Oppslutning",
    category: "provetaking",
    definition: "Å løse opp prøven fullstendig, ofte med syre og varme.",
    aliases: ["digestion", "mikrobølge"],
    status: "utkast",
  },
  {
    slug: "provemengde",
    title: "Prøvemengde",
    category: "provetaking",
    definition: "Hvor mye prøve som tas inn i analysen.",
    aliases: ["innveid", "mengde"],
    status: "utkast",
  },
  {
    slug: "molaritet",
    title: "Molaritet",
    category: "enheter",
    definition: "Antall mol stoff per liter løsning.",
    aliases: ["mol/l", "konsentrasjon", "m"],
    status: "utkast",
  },
  {
    slug: "ppm",
    title: "ppm",
    category: "enheter",
    definition: "Deler per million, altså milligram per kilo eller milligram per liter.",
    aliases: ["mg/kg", "deler", "per", "million"],
    status: "utkast",
  },
  {
    slug: "molmasse",
    title: "Molmasse",
    category: "enheter",
    definition: "Massen til ett mol av et stoff.",
    aliases: ["g/mol", "molvekt"],
    status: "utkast",
  },
  {
    slug: "sienheter",
    title: "SI-enheter",
    category: "enheter",
    definition: "Det internasjonale enhetssystemet som all måling refereres til.",
    aliases: ["si", "enhet", "meter", "kilogram"],
    status: "utkast",
  },
  {
    slug: "masseprosent",
    title: "Masseprosent",
    category: "enheter",
    definition: "Massen av stoffet som andel av total masse.",
    aliases: ["vektprosent", "w/w"],
    status: "utkast",
  },
  {
    slug: "grovfeil",
    title: "Grov feil",
    category: "feilkilder",
    definition: "En enkeltstående feil, som en forbyttet prøve eller en feil beregning, som ikke kan behandles statistisk.",
    aliases: ["blunder", "tabbe", "forbyttet"],
    status: "utkast",
  },
];
