import type { Source } from "./schema";

const EURACHEM_2025 = "https://eurachem.org/index.php/publications/guides/mv";

/** Autoritative fagkilder som kan gjenbrukes mellom begreper. */
export const SOURCES = {
  vimAccuracy: { title: "JCGM VIM — Measurement accuracy", url: "https://jcgm.bipm.org/vim/en/2.13.html", locator: "VIM 2.13" },
  vimTrueness: { title: "JCGM VIM — Measurement trueness", url: "https://jcgm.bipm.org/vim/en/2.14.html", locator: "VIM 2.14" },
  vimPrecision: { title: "JCGM VIM — Measurement precision", url: "https://jcgm.bipm.org/vim/en/2.15.html", locator: "VIM 2.15" },
  vimBias: { title: "JCGM VIM — Measurement bias", url: "https://jcgm.bipm.org/vim/en/2.18.html", locator: "VIM 2.18" },
  vimRepeatabilityCondition: { title: "JCGM VIM — Repeatability condition of measurement", url: "https://jcgm.bipm.org/vim/en/2.20.html", locator: "VIM 2.20" },
  vimRepeatability: { title: "JCGM VIM — Measurement repeatability", url: "https://jcgm.bipm.org/vim/en/2.21.html", locator: "VIM 2.21" },
  vimIntermediatePrecisionCondition: { title: "JCGM VIM — Intermediate precision condition of measurement", url: "https://jcgm.bipm.org/vim/en/2.22.html", locator: "VIM 2.22" },
  vimIntermediatePrecision: { title: "JCGM VIM — Intermediate measurement precision", url: "https://jcgm.bipm.org/vim/en/2.23.html", locator: "VIM 2.23" },
  vimReproducibilityCondition: { title: "JCGM VIM — Reproducibility condition of measurement", url: "https://jcgm.bipm.org/vim/en/2.24.html", locator: "VIM 2.24" },
  vimReproducibility: { title: "JCGM VIM — Measurement reproducibility", url: "https://jcgm.bipm.org/vim/en/2.25.html", locator: "VIM 2.25" },
  vimUncertainty: { title: "JCGM VIM — Measurement uncertainty", url: "https://jcgm.bipm.org/vim/en/2.26.html", locator: "VIM 2.26" },
  vimExpandedUncertainty: { title: "JCGM VIM — Expanded measurement uncertainty", url: "https://jcgm.bipm.org/vim/en/2.35.html", locator: "VIM 2.35" },
  vimCoverageFactor: { title: "JCGM VIM — Coverage factor", url: "https://jcgm.bipm.org/vim/en/2.38.html", locator: "VIM 2.38" },
  vimCalibration: { title: "JCGM VIM — Calibration", url: "https://jcgm.bipm.org/vim/en/2.39.html", locator: "VIM 2.39" },
  vimTraceability: { title: "JCGM VIM — Metrological traceability", url: "https://jcgm.bipm.org/vim/en/2.41.html", locator: "VIM 2.41" },
  vimVerification: { title: "JCGM VIM — Verification", url: "https://jcgm.bipm.org/vim/en/2.44.html", locator: "VIM 2.44" },
  vimValidation: { title: "JCGM VIM — Validation", url: "https://jcgm.bipm.org/vim/en/2.45.html", locator: "VIM 2.45" },
  vimSensitivity: { title: "JCGM VIM — Sensitivity of a measuring system", url: "https://jcgm.bipm.org/vim/en/4.12.html", locator: "VIM 4.12" },
  vimSelectivity: { title: "JCGM VIM — Selectivity of a measuring system", url: "https://jcgm.bipm.org/vim/en/4.13.html", locator: "VIM 4.13" },
  vimDetectionLimit: { title: "JCGM VIM — Detection limit", url: "https://jcgm.bipm.org/vim/en/4.18.html", locator: "VIM 4.18" },
  vimInstrumentalDrift: { title: "JCGM VIM — Instrumental drift", url: "https://jcgm.bipm.org/vim/en/4.21.html", locator: "VIM 4.21" },
  vimCalibrationCurve: { title: "JCGM VIM — Calibration curve", url: "https://jcgm.bipm.org/vim/en/4.31.html", locator: "VIM 4.31" },
  eurachem2025: { title: "Eurachem — The Fitness for Purpose of Analytical Methods, 3rd ed. (2025)", url: EURACHEM_2025 },
  eurachemQac2016: { title: "Eurachem/CITAC — Quality in Analytical Chemistry (2016)", url: "https://eurachem.org/images/stories/Guides/pdf/Eurachem_CITAC_QAC_2016_EN.pdf" },
  iupacMetrology2021: { title: "IUPAC Recommendations — Metrological and quality concepts in analytical chemistry", url: "https://doi.org/10.1515/pac-2019-0819" },
  iupacCalibrationFunction: { title: "IUPAC Gold Book — Calibration function", url: "https://goldbook.iupac.org/terms/view/C00778" },
  iupacLinearitySystem: { title: "IUPAC Gold Book — Linearity of a measuring system", url: "https://goldbook.iupac.org/terms/view/08023" },
  iupacLinearityCalibration: { title: "IUPAC Gold Book — Linearity of calibration", url: "https://goldbook.iupac.org/terms/view/08024" },
  iupacQuantificationLimit: { title: "IUPAC Gold Book — Limit of quantification", url: "https://goldbook.iupac.org/terms/view/08022" },
  iupacWorkingInterval: { title: "IUPAC Gold Book — Working interval", url: "https://goldbook.iupac.org/terms/view/08051" },
  iupacRecovery: { title: "IUPAC Gold Book — Recovered quantity value ratio", url: "https://goldbook.iupac.org/terms/view/08039" },
  iupacBlank: { title: "IUPAC Gold Book — Blank material", url: "https://goldbook.iupac.org/terms/view/08010" },
  iupacInternalStandard: { title: "IUPAC Gold Book — Internal standard", url: "https://goldbook.iupac.org/terms/view/I03108" },
  iupacSurrogateInternalStandard: { title: "IUPAC Gold Book — Surrogate internal standard", url: "https://goldbook.iupac.org/terms/view/12589" },
  iupacStandardAddition: { title: "IUPAC Gold Book — Measurement procedure with standard addition", url: "https://goldbook.iupac.org/terms/view/08030" },
  iupacExternalCalibration: { title: "IUPAC Gold Book — External calibration", url: "https://goldbook.iupac.org/terms/view/10174" },
  iupacMatrixMatchedCalibration: { title: "IUPAC Gold Book — Matrix-matched calibration", url: "https://goldbook.iupac.org/terms/view/10180" },
  iupacMatrixEffect: { title: "IUPAC Gold Book — Matrix effect", url: "https://goldbook.iupac.org/terms/view/M03759" },
  iupacPeakResolution: { title: "IUPAC Gold Book — Peak resolution in chromatography", url: "https://goldbook.iupac.org/terms/view/P04465" },
  nistStandardDeviation: { title: "NIST/SEMATECH e-Handbook — Measures of Scale", url: "https://www.itl.nist.gov/div898/handbook/eda/section3/eda356.htm" },
  nistWeightedLeastSquares: { title: "NIST/SEMATECH e-Handbook — Weighted Least Squares Regression", url: "https://www.itl.nist.gov/div898/handbook/pmd/section1/pmd143.htm" },
  nistControlChart: { title: "NIST/SEMATECH e-Handbook — Shewhart control chart", url: "https://www.itl.nist.gov/div898/handbook/mpc/section2/mpc221.htm" },
} as const satisfies Record<string, Source>;
