import type { Source } from "./schema";

const EURACHEM_2025 = "https://eurachem.org/index.php/publications/guides/mv";
const EURACHEM_QAC_2026 = "https://eurachem.org/index.php/publications/guides/qa";

/** Autoritative fagkilder som kan gjenbrukes mellom begreper. */
export const SOURCES = {
  vimAccuracy: { title: "JCGM VIM — Measurement accuracy", url: "https://jcgm.bipm.org/vim/en/2.13.html", locator: "VIM 2.13" },
  vimTrueness: { title: "JCGM VIM — Measurement trueness", url: "https://jcgm.bipm.org/vim/en/2.14.html", locator: "VIM 2.14" },
  vimPrecision: { title: "JCGM VIM — Measurement precision", url: "https://jcgm.bipm.org/vim/en/2.15.html", locator: "VIM 2.15" },
  vimBias: { title: "JCGM VIM — Measurement bias", url: "https://jcgm.bipm.org/vim/en/2.18.html", locator: "VIM 2.18" },
  vimRepeatabilityCondition: { title: "JCGM VIM — Repeatability condition of measurement", url: "https://jcgm.bipm.org/vim/en/2.20.html", locator: "VIM 2.20" },
  vimRepeatability: { title: "JCGM VIM — Measurement repeatability", url: "https://jcgm.bipm.org/vim/en/2.21.html", locator: "VIM 2.21" },
  vimIntermediatePrecisionCondition: { title: "JCGM VIM — Intermediate precision condition of measurement", url: "https://jcgm.bipm.org/vim/en/2.22.html", locator: "VIM 2.22" },
  vimIntermediatePrecision: { title: "JCGM VIM — Intermediate measurement precision", url: "https://jcgm.bipm.org/vim/en/2.23.html", locator: "VIM 2.23" },
  vimReproducibilityCondition: { title: "JCGM VIM — Reproducibility condition of measurement", url: "https://jcgm.bipm.org/vim/en/2.24.html", locator: "VIM 2.24" },
  vimReproducibility: { title: "JCGM VIM — Measurement reproducibility", url: "https://jcgm.bipm.org/vim/en/2.25.html", locator: "VIM 2.25" },
  vimUncertainty: { title: "JCGM VIM — Measurement uncertainty", url: "https://jcgm.bipm.org/vim/en/2.26.html", locator: "VIM 2.26" },
  vimExpandedUncertainty: { title: "JCGM VIM — Expanded measurement uncertainty", url: "https://jcgm.bipm.org/vim/en/2.35.html", locator: "VIM 2.35" },
  vimCoverageFactor: { title: "JCGM VIM — Coverage factor", url: "https://jcgm.bipm.org/vim/en/2.38.html", locator: "VIM 2.38" },
  vimCalibration: { title: "JCGM VIM — Calibration", url: "https://jcgm.bipm.org/vim/en/2.39.html", locator: "VIM 2.39" },
  vimTraceability: { title: "JCGM VIM — Metrological traceability", url: "https://jcgm.bipm.org/vim/en/2.41.html", locator: "VIM 2.41" },
  vimVerification: { title: "JCGM VIM — Verification", url: "https://jcgm.bipm.org/vim/en/2.44.html", locator: "VIM 2.44" },
  vimValidation: { title: "JCGM VIM — Validation", url: "https://jcgm.bipm.org/vim/en/2.45.html", locator: "VIM 2.45" },
  vimBackgroundIndication: { title: "JCGM VIM — Blank indication / background indication", url: "https://jcgm.bipm.org/vim/en/4.2.html", locator: "VIM 4.2" },
  vimSensitivity: { title: "JCGM VIM — Sensitivity of a measuring system", url: "https://jcgm.bipm.org/vim/en/4.12.html", locator: "VIM 4.12" },
  vimSelectivity: { title: "JCGM VIM — Selectivity of a measuring system", url: "https://jcgm.bipm.org/vim/en/4.13.html", locator: "VIM 4.13" },
  vimDetectionLimit: { title: "JCGM VIM — Detection limit", url: "https://jcgm.bipm.org/vim/en/4.18.html", locator: "VIM 4.18" },
  vimInstrumentalDrift: { title: "JCGM VIM — Instrumental drift", url: "https://jcgm.bipm.org/vim/en/4.21.html", locator: "VIM 4.21" },
  vimCalibrationCurve: { title: "JCGM VIM — Calibration curve", url: "https://jcgm.bipm.org/vim/en/4.31.html", locator: "VIM 4.31" },
  eurachem2025: { title: "Eurachem — The Fitness for Purpose of Analytical Methods, 3rd ed. (2025)", url: EURACHEM_2025 },
  eurachemQac2016: { title: "Eurachem/CITAC — Quality in Analytical Chemistry (2016)", url: "https://eurachem.org/images/stories/Guides/pdf/Eurachem_CITAC_QAC_2016_EN.pdf" },
  eurachemQac2026: { title: "Eurachem/CITAC — Guide to Quality in Analytical Chemistry, 4th ed. (2026)", url: EURACHEM_QAC_2026 },
  iupacMetrology2021: { title: "IUPAC Recommendations — Metrological and quality concepts in analytical chemistry", url: "https://doi.org/10.1515/pac-2019-0819" },
  iupacCalibrationFunction: { title: "IUPAC Gold Book — Calibration function", url: "https://goldbook.iupac.org/terms/view/C00778" },
  iupacLinearitySystem: { title: "IUPAC Gold Book — Linearity of a measuring system", url: "https://goldbook.iupac.org/terms/view/08023" },
  iupacLinearityCalibration: { title: "IUPAC Gold Book — Linearity of calibration", url: "https://goldbook.iupac.org/terms/view/08024" },
  iupacQuantificationLimit: { title: "IUPAC Gold Book — Limit of quantification", url: "https://goldbook.iupac.org/terms/view/08022" },
  iupacWorkingInterval: { title: "IUPAC Gold Book — Working interval", url: "https://goldbook.iupac.org/terms/view/08051" },
  iupacRecovery: { title: "IUPAC Gold Book — Recovered quantity value ratio", url: "https://goldbook.iupac.org/terms/view/08039" },
  iupacBackgroundIndication: { title: "IUPAC Gold Book — Background indication", url: "https://goldbook.iupac.org/terms/view/08007" },
  iupacInterferent: { title: "IUPAC Gold Book — Interferent", url: "https://goldbook.iupac.org/terms/view/08019" },
  iupacInterference: { title: "IUPAC Gold Book — Interference", url: "https://goldbook.iupac.org/terms/view/I03089" },
  iupacBlank: { title: "IUPAC Gold Book — Blank material", url: "https://goldbook.iupac.org/terms/view/08010" },
  iupacIonSuppression: { title: "IUPAC Gold Book — Ion suppression", url: "https://goldbook.iupac.org/terms/view/12445" },
  iupacIonEnhancement: { title: "IUPAC Gold Book — Ion enhancement", url: "https://goldbook.iupac.org/terms/view/12437" },
  iupacCarryOver: { title: "IUPAC Gold Book — Carry-over", url: "https://goldbook.iupac.org/terms/view/C00866" },
  iupacInternalStandard: { title: "IUPAC Gold Book — Internal standard", url: "https://goldbook.iupac.org/terms/view/I03108" },
  iupacSurrogateInternalStandard: { title: "IUPAC Gold Book — Surrogate internal standard", url: "https://goldbook.iupac.org/terms/view/12589" },
  iupacStandardAddition: { title: "IUPAC Gold Book — Measurement procedure with standard addition", url: "https://goldbook.iupac.org/terms/view/08030" },
  iupacExternalCalibration: { title: "IUPAC Gold Book — External calibration", url: "https://goldbook.iupac.org/terms/view/10174" },
  iupacMatrixMatchedCalibration: { title: "IUPAC Gold Book — Matrix-matched calibration", url: "https://goldbook.iupac.org/terms/view/10180" },
  iupacMatrixEffect: { title: "IUPAC Gold Book — Matrix effect", url: "https://goldbook.iupac.org/terms/view/M03759" },
  iupacPeakResolution: { title: "IUPAC Gold Book — Peak resolution in chromatography", url: "https://goldbook.iupac.org/terms/view/P04465" },
  iupacArithmeticMean: { title: "IUPAC Gold Book — Arithmetic mean", url: "https://goldbook.iupac.org/terms/view/A00440" },
  iupacMedian: { title: "IUPAC Gold Book — Median", url: "https://goldbook.iupac.org/terms/view/M03806" },
  iupacDegreesFreedom: { title: "IUPAC Gold Book — Degrees of freedom", url: "https://goldbook.iupac.org/terms/view/D01572" },
  iupacConfidenceLevel: { title: "IUPAC Gold Book — Confidence level", url: "https://goldbook.iupac.org/terms/view/C01246" },
  iupacConfidenceLimits: { title: "IUPAC Gold Book — Confidence limits", url: "https://goldbook.iupac.org/terms/view/C01247" },
  iupacCorrelationCoefficient: { title: "IUPAC Gold Book — Correlation coefficient", url: "https://goldbook.iupac.org/terms/view/C01347" },
  iupacRegressionAnalysis: { title: "IUPAC Gold Book — Regression analysis", url: "https://goldbook.iupac.org/terms/view/RT06979" },
  iupacLeastSquares: { title: "IUPAC Gold Book — Least squares regression", url: "https://goldbook.iupac.org/terms/view/10149" },
  iupacOrdinaryLeastSquares: { title: "IUPAC Gold Book — Ordinary least squares regression", url: "https://goldbook.iupac.org/terms/view/10154" },
  nistStandardDeviation: { title: "NIST/SEMATECH e-Handbook — Measures of Scale", url: "https://www.itl.nist.gov/div898/handbook/eda/section3/eda356.htm" },
  nistMeasuresLocation: { title: "NIST/SEMATECH e-Handbook — Measures of Location", url: "https://www.itl.nist.gov/div898/handbook/eda/section3/eda351.htm" },
  nistConfidenceIntervals: { title: "NIST/SEMATECH e-Handbook — Confidence Limits for the Mean", url: "https://www.itl.nist.gov/div898/handbook/eda/section3/eda352.htm" },
  nistTTest: { title: "NIST/SEMATECH e-Handbook — Tests for a Process Mean", url: "https://www.itl.nist.gov/div898/handbook/prc/section2/prc22.htm" },
  nistTwoSampleTTest: { title: "NIST/SEMATECH e-Handbook — Two-Sample t-Test for Equal Means", url: "https://www.itl.nist.gov/div898/handbook/eda/section3/eda353.htm" },
  nistFTest: { title: "NIST/SEMATECH e-Handbook — F-Test for Equality of Two Variances", url: "https://www.itl.nist.gov/div898/handbook/eda/section3/eda359.htm" },
  nistLinearLeastSquares: { title: "NIST/SEMATECH e-Handbook — Linear Least Squares Regression", url: "https://www.itl.nist.gov/div898/handbook/pmd/section1/pmd141.htm" },
  nistNormalDistribution: { title: "NIST/SEMATECH e-Handbook — Normal Distribution", url: "https://www.itl.nist.gov/div898/handbook/eda/section3/eda3661.htm" },
  nistOutliers: { title: "NIST/SEMATECH e-Handbook — Detection of Outliers", url: "https://www.itl.nist.gov/div898/handbook/eda/section3/eda35h.htm" },
  nistSignificance: { title: "NIST/SEMATECH e-Handbook — Critical Values and p-values", url: "https://www.itl.nist.gov/div898/handbook/prc/section1/prc131.htm" },
  nistWeightedLeastSquares: { title: "NIST/SEMATECH e-Handbook — Weighted Least Squares Regression", url: "https://www.itl.nist.gov/div898/handbook/pmd/section1/pmd143.htm" },
  nistControlChart: { title: "NIST/SEMATECH e-Handbook — Shewhart control chart", url: "https://www.itl.nist.gov/div898/handbook/mpc/section2/mpc221.htm" },
} as const satisfies Record<string, Source>;
