/**
 * Identifikatorene for demonstrasjonene. Holdes adskilt fra komponentene selv
 * slik at innholdsvalidering kan kjøre uten å laste React-komponenter.
 */
export const DEMO_IDS = [
  "presisjon-spredning",
  "repeterbarhet-serie",
  "intermediar-forhold",
  "reproduserbarhet-lab",
  "riktighet-skiver",
  "skjevhet-referanse",
  "gjenvinning-spike",
  "usikkerhetsbudsjett",
  "utvidet-intervall",
  "dekningsfaktor-k",
  "selektivitet-interferens",
  "spesifisitet-terminologi",
  "folsomhet-stigning",
  "robusthet-variasjon",
  "sporbarhet-kjede",
  "validering-formal",
  "verifisering-krav",
  "kontrollkort-serie",
  "linearitet-kurve",
  "deteksjonsgrense-stoy",
  "internstandard-forhold",
  "standardaddisjon-steg",
  "blindprove-typer",
  "kalibreringskurve-punkter",
  "kvantifiseringsgrense-krav",
  "responsfaktor-forhold",
  "arbeidsomrade-grenser",
  "ettpunktskalibrering-ankring",
  "vektet-regresjon-vekter",
  "nullpunkt-skjaring",
  "drift-tidsserie",
  "kontrollprove-vakt",
  "ekstern-kalibrering-separat",
  "matrikstilpasset-kalibrering-matriks",
  "matriseeffekt-matrikser",
  "ionesuppresjon-respons",
  "ioneforsterkning-respons",
  "interferens-signal",
  "bakgrunnssignal-nivaa",
  "matriksblank-sammenligning",
  "kontaminering-kilde",
  "krysskontaminering-sekvens",
  "provelagring-betingelser",
  "standardavvik-formel",
  "opplosning-topper",
] as const;

export type DemoId = (typeof DEMO_IDS)[number];
